import { useEffect, useRef, useState } from 'react';
import './forward.scss';
const steps=[
 ['Discover','Start with the workflow.','Work alongside stakeholders to understand the problem, the data, and what a useful outcome looks like.','Business context → clear problem'],
 ['Build','Turn ambiguity into a working system.','Connect models, retrieval, and tools. Make assumptions explicit and put a useful prototype in front of people early.','Context + tools → working prototype'],
 ['Deploy','Bridge the demo and daily use.','Integrate with existing systems, add human review, and make failures visible through tracing and operational checks.','Prototype → integrated workflow'],
 ['Iterate','Let real usage shape the next version.','Use feedback and evaluation to refine reliability, cost, and the experience of the people using the system.','Feedback → next improvement']
];
export default function Forward(){
 const [active,setActive]=useState(0),[playing,setPlaying]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches),[visible,setVisible]=useState(false);
 const ref=useRef(null);
 useEffect(()=>{const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.2});observer.observe(ref.current);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(!playing||!visible)return;const timer=setTimeout(()=>{setActive(value=>(value+1)%steps.length);},4000);return()=>clearTimeout(timer);},[active,playing,visible]);
 return <section className={`forward ${visible?'in-view':''} ${playing?'is-playing':''}`} id="forward" ref={ref} aria-labelledby="forward-heading"><header><p className="fde-eyebrow">HOW I WORK / FROM CONTEXT TO DELIVERY</p><h2 id="forward-heading">Close to the problem.<br/><span>Hands on with the solution.</span></h2><p className="fde-intro">I connect business context with AI engineering—from the first conversation to a workflow people can use. My approach brings stakeholders, data, and delivery into the same loop.</p></header>
 <div className="fde-workbench"><div className="fde-visual" aria-hidden="true"><div className="fde-orbit"/><svg viewBox="0 0 520 320" fill="none"><path className="fde-route" d="M95 80H425V245H95Z" stroke="currentColor" strokeDasharray="5 8"/><path d="M95 80 260 160 425 80M95 245l165-85 165 85" stroke="currentColor" opacity=".2"/>{[[95,80],[425,80],[425,245],[95,245]].map(([x,y],i)=><g key={i} className={active===i?'fde-node active':'fde-node'}><circle cx={x} cy={y} r="36" fill="var(--surface)" stroke="currentColor"/><circle cx={x} cy={y} r="43" stroke="currentColor" className="fde-pulse"/><text x={x} y={y+5} textAnchor="middle" fill="currentColor" fontSize="14">0{i+1}</text><text x={x} y={y+60} textAnchor="middle" fill="currentColor" fontSize="12">{steps[i][0]}</text></g>)}<g className="fde-core"><path d="m260 111 47 25v49l-47 25-47-25v-49Z" fill="var(--surface-raised)" stroke="currentColor"/><path d="m213 136 47 25 47-25M260 161v49" stroke="currentColor"/><text x="260" y="147" textAnchor="middle" fill="currentColor" fontSize="13">BUILD</text></g></svg><div className="fde-signal"><span/> HUMAN CONTEXT + ENGINEERING</div></div>
 <div className="fde-panel"><div className="fde-panel-top"><span>DELIVERY LOOP</span><button type="button" onClick={()=>{if(playing)setPlaying(false);else{setActive(0);setPlaying(true);}}}>{playing?'Pause walkthrough':'Play walkthrough'} {playing?'Ⅱ':'▷'}</button></div><div className="fde-steps" aria-label="Explore the delivery loop">{steps.map(([label],i)=><button key={label} type="button" aria-pressed={active===i} onClick={()=>{setPlaying(false);setActive(i);}}>{label}</button>)}</div><div key={active} className="fde-detail" aria-live={playing ? "off" : "polite"}><span className="fde-eyebrow">0{active+1} / {steps[active][0].toUpperCase()}</span><h3>{steps[active][1]}</h3><p>{steps[active][2]}</p><code>{steps[active][3]}</code></div><p className="fde-footnote">My delivery approach · explore each stage</p></div></div>
 </section>;
}

