const nodes=[
 {id:'ticket',x:15,y:114,w:120,title:'New request',sub:'Message trigger',icon:'↳',phase:0,tone:'teal'},
 {id:'context',x:165,y:114,w:130,title:'Retrieve context',sub:'Policy + order data',icon:'▤',phase:1,tone:'blue'},
 {id:'route',x:325,y:114,w:120,title:'AI router',sub:'Intent / risk check',icon:'◇',phase:2,tone:'purple'},
 {id:'escalate',x:495,y:14,w:140,title:'Escalate',sub:'Specialist review',icon:'◎',phase:-1,tone:'rose'},
 {id:'draft',x:495,y:114,w:140,title:'Draft response',sub:'Grounded answer',icon:'✧',phase:2,tone:'purple'},
 {id:'log',x:495,y:214,w:140,title:'Log feedback',sub:'No reply required',icon:'▤',phase:-1,tone:'blue'},
 {id:'review',x:675,y:114,w:130,title:'Human review',sub:'Approve or revise',icon:'◎',phase:3,tone:'amber'},
 {id:'ready',x:845,y:114,w:125,title:'Ready to send',sub:'Demo ends here',icon:'✓',phase:4,tone:'teal'}
];
const edges=[['M135 149H165',1],['M295 149H325',2],['M445 149H495',2],['M445 149H465Q475 149 475 139V59Q475 49 485 49H495',-1],['M445 149H465Q475 149 475 159V239Q475 249 485 249H495',-1],['M635 149H675',3],['M805 149H845',4]];
export default function WorkflowGraph({step}){
 return <div className="workflow-map-scroll" tabIndex={0} role="region" aria-label="Automation diagram. Scroll horizontally on small screens."><svg className="workflow-map" viewBox="0 0 990 310" role="img" aria-labelledby="workflow-map-title workflow-map-desc"><title id="workflow-map-title">Support request automation with branching routes</title><desc id="workflow-map-desc">New request connects to retrieval and an AI router. The router branches to specialist escalation, response drafting, or feedback logging. The animated example follows response drafting, then human review, then a ready-to-send draft. No message is sent.</desc><defs><marker id="workflow-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0 10 5 0 10Z" fill="currentColor"/></marker></defs>{edges.map(([d,phase],i)=><g key={i} className={`workflow-edge ${phase>0&&step>=phase?'traced':''}`}><path d={d} markerEnd="url(#workflow-arrow)"/>{phase===step&&<path className="workflow-packet" d={d}/>}</g>)}<text x="383" y="37" className="workflow-branch-label">HIGH RISK</text><text x="455" y="107" className="workflow-branch-label">INQUIRY</text><text x="382" y="272" className="workflow-branch-label">FEEDBACK</text>{nodes.map(node=><g key={node.id} transform={`translate(${node.x} ${node.y})`} className={`workflow-node tone-${node.tone} ${step===node.phase?'current':''}`}><rect width={node.w} height="70" rx="10"/><circle cx="0" cy="35" r="3" className="workflow-port"/><circle cx={node.w} cy="35" r="3" className="workflow-port"/><text x="12" y="24" className="workflow-icon">{node.icon}</text><text x="32" y="24" className="workflow-kind">{node.id==='review'||node.id==='escalate'?'HUMAN':'AUTOMATION'}</text><text x="12" y="43" className="workflow-node-title">{node.title}</text><text x="12" y="59" className="workflow-node-sub">{node.sub}</text></g>)}</svg></div>;
}
